<a href="https://colab.research.google.com/github/barkamoljon/data_science_praktikum/blob/main/mohirdev_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy kutubxonasiga doir bilimlaringizni mustaxkamlash uchun mashqlar

Hurmatli o'quvchi, bilimingizni yanada mustaxkamlashingiz va chuqurroq ko'nikmalarga ega bo'lishingiz uchun sizga topshiriqlar tayyorladik. Sizga yengillik yaratish maqsadida topshiriqni aynan qanday funksiyalar yordamida amalga oshirishingiz mumkin ekanini
 `💡Ishora` ko'rinishida yozdik!

#### 1. NumPy kutubxonasini `np` nomi ostida yuklang va numpy kutubxonasini chop eting.

versiya va konfiguratsiyani tekshiring.


`💡Ishora` import … as` and `np.__version__, np.show_config

In [1]:
import numpy as np

#### 2. Raqamli qiymatlar ro'yxatini bir o'lchovli NumPy massiviga aylantiring!

`💡Ishora` numpy.array

In [2]:
sonlar =  [1,2,3,4,5,6]
numbers = np.array(sonlar)

#### 3. Qiymatlari noldan iborat bo'lgan to'qqiz o'lchovli massiv yarating.



`💡Ishora` np.zeros

In [3]:
massiv = np.zeros(shape =(3,3))
massiv

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

#### 4. Massiv yarating va uning xotira hajmini toping.



`💡Ishora` size, itemsize

In [4]:
massiv.size

9

#### 5. NumPy kutubxonasidagi add funksiyasi hujjatlarini buyruq satridan qanday olishi mumkin?


`💡Ishora` np.info

In [5]:
np.info(np.add)

#### 6. Shunday vekor yaratingki u o'n ikki o'lchamda va qiymatlari noldan iborat bo'lsin, lekin vektorning oltinchi qiymati 1 ga teng bo'lsin.



`💡Ishora` array[12]

In [6]:
vectors = np.zeros(12)
vectors[5] = 1
vectors

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.])

#### 7. Qiymatlari 20 dan 59 gacha bo'lgan vektor yarating.



`💡Ishora` arange

In [7]:
qiymatlar = np.arange(20, 59)
qiymatlar

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
       54, 55, 56, 57, 58])

#### 8. Vektor yarating va uni teskari o'zgartiring
(birinchi element oxirgisi bo'lsin)



`💡Ishora` array[::-1]

In [8]:
qiymatlar = qiymatlar[::-1]
qiymatlar

array([58, 57, 56, 55, 54, 53, 52, 51, 50, 49, 48, 47, 46, 45, 44, 43, 42,
       41, 40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25,
       24, 23, 22, 21, 20])

#### 9. 12 dan 20 gacha bo'lgan qiymatlarga ega 3x3 matritsa yarating.


`💡Ishora` reshape

In [9]:
uchkarra_uch =  np.arange(12, 21).reshape(3,3)
uchkarra_uch

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20]])

#### 10. Quyidagi matritsadan foydalanib nolga teng bo'lmagan elementlarning indekslarini toping.
[3, 7, 0, 0, 9, 0]





`💡Ishora` np.nonzero

In [10]:
np.nonzero([3, 7, 0, 0, 9, 0])

(array([0, 1, 4]),)

#### 11. Tasodifiy qiymatlar bilan 2x2x2 o'lchovidagi massiv yarating.


`💡Ishora` np.random.random

In [11]:
floats = np.random.random((2,2,2))
floats

array([[[0.55802604, 0.07270554],
        [0.07055596, 0.00933596]],

       [[0.25294848, 0.85542869],
        [0.01309885, 0.28619142]]])

#### 12. Tasodifiy sonlardan tashkil topgan 9X9 o'lchamidagi massiv yarating. So'ng uning eng katta va eng kichik qiymatlarini toping


`💡Ishora` min, max

In [12]:
numbers = np.random.random((9,9))
print(numbers.min())
print(numbers.max())

0.03164014844411989
0.9926294083506053


#### 13. Quyidagi misol qanday natija beradi?


```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.7 == 7 * 0.1
```


In [13]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.7 == 7 * 0.1

False

`💡Ishora` NaN = not a number, inf = infinity

In [14]:
#Berilgan misollar natijalari quyidagilar:

#1. `0 * np.nan`: 0 ni `np.nan` bilan ko'paytirish natijasida doimiy `np.nan` bo'ladi. Bu sababli, `np.nan` bilan amal qiladigan har qanday arifmetik amal natijada `np.nan` (NaN qiymati) hosil qiladi.
#   Natija: `nan`

#2. `np.nan == np.nan`: Ikki NaN qiymatni tenglik operatori (`==`) bilan solishtirish natijada doimiy False qaytaradi. Bu sababli, NaN "son emas" deb hisoblanadi va NaN bilan, undan tashqari, NaN o'ziningga ham teng emas.
#   Natija: `False`

#3. `np.inf > np.nan`: Infinity (`np.inf`) ni NaN (`np.nan`) bilan solishtirish natijada katta miqyosida False qaytaradi. NaN tartiblangan bo'lmagan deb hisoblanadi, shuning uchun NaN bilan solishtirish barcha natijalar False bo'ladi.
#   Natija: `False`

#4. `np.nan - np.nan`: Bir NaN qiymatini boshqa bir NaN qiymatidan ayirish natijasida doimiy `np.nan` bo'ladi. Ko'paytirish kabi, np.nan ni o'z ichiga olgan har qanday arifmetik amal natijada `np.nan` hosil qiladi.
#   Natija: `nan`

#5. `np.nan in set([np.nan])`: `in` operatori, to'plikda a'zo bo'lishni tekshiradi. `np.nan` NaN qiymati bo'lsa ham, u `np.nan` ni o'z ichiga olgan to'plik a'zosi hisoblanadi. Bu sababli, NaN qiymatlari to'plik va lug'atlar ichida a'zo bo'lgan va teng hisoblanadigan bo'lishi mumkin.
#   Natija: `True`

#6. `0.7 == 7 * 0.1`: Bu solishtirma 0.7 nuqta sanoqqi qiymati va 7 ni 0.1 bilan ko'paytirish natijasiga tengmi yoki emasmi tekshiradi. Sanoq sifatli hisoblashning joriy cheklovlariga asoslanib, natija aniqligi aniq ravishda 0.7 bo'lmasligi mumkin, shuning uchun solishtirma False qaytara oladi.
#   Natija: `False`

#### 14. O'lchamlari 6x3 va 3x4 bo'lgan martitsa yarating, so'ng ularning  ko'paytmasini hisoblang.



`💡Ishora` np.dot` or `np.ones

In [15]:
a = np.ones(shape=(6,3))
b = np.ones(shape=(3,4))
np.dot(a,b)

array([[3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.]])

#### 15. Quyidagi misol qanday natija beradi?

```python
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [16]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 16. NumPy kutubxonasi yordamida ikkita massivni solishtiring va ular usida quyidagi amallarni bajaring.

```python
Array a: [1 2]
Array b: [4 5]
a > b
[False False]
a >= b
[False False]
a < b
[ True True]
a <= b
[ True True]
```

In [17]:
a = [1, 2]
b = [4, 5]
print(a > b)
print(a >= b)
print(a < b)
print(a <= b)

False
False
True
True


#### 17. Quyidagi misol qanday natija beradi?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [18]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


<ipython-input-18-2a10de0ee61b>:1: RuntimeWarning: invalid value encountered in true_divide
  print(np.array(0) / np.array(0))
<ipython-input-18-2a10de0ee61b>:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


#### 18. Ikkita massiv yarating va ular orasidagi umumiy qiymatlarni toping


`💡Ishora` np.intersect1d

In [19]:
q = np.random.random(size=None)
w = np.random.random(size=None)
np.intersect1d(q,w)

array([], dtype=float64)

#### 19. Tasodifiy sonlardan iborat bo'lgan massiv yarating, so'ng ularni quyida berilgan 4 xil usul yordamida musbat sonlarning butun qismini ajratib oling.

`💡Ishora` %, np.floor, astype, np.trunc

In [20]:
import numpy as np
np.random.seed(42)
array = np.random.randn(10)

print("Asl array:")
print(array)

# Metod 1: Modul operator (%)
metod1 = array[array > 0]
print("\nMetod 1 (Modul operator) :")
print(metod1)

# Metod 2: np.floor()
metod2 = np.floor(array[array>0])
print("\nMetod 2 (np.floor) :")
print(metod2)

# Metod 3: astype()
metod3 = (array[array > 0]).astype(int)
print("\nMetod 3 (astype) :")
print(metod3)

# Metod 4: np.trunc()
metod4 = np.trunc(array[array>0])
print("\nMetod 4 (np.trunc) :")
print(metod4)

Asl array:
[ 0.49671415 -0.1382643   0.64768854  1.52302986 -0.23415337 -0.23413696
  1.57921282  0.76743473 -0.46947439  0.54256004]

Metod 1 (Modul operator) :
[0.49671415 0.64768854 1.52302986 1.57921282 0.76743473 0.54256004]

Metod 2 (np.floor) :
[0. 0. 1. 1. 0. 0.]

Metod 3 (astype) :
[0 0 1 1 0 0]

Metod 4 (np.trunc) :
[0. 0. 1. 1. 0. 0.]


#### 20. O'lchovlari 3x3 matritsa yarating, ularning qator qiymatlari 0 dan 2 gacha bo'lsin.



`💡Ishora` np.arange

In [21]:
np.random.randint(3, size=(3,3))

array([[0, 0, 1],
       [1, 0, 0],
       [0, 2, 2]])

#### 21. O'chamlari 10 bo'lgan tasodifiy vektor yarating va uni o'sish tartibida chiqaruvchi dastur tuzing.



`💡Ishora` sort

In [22]:
onlik = np.random.rand(10)
tartiblanganlar = np.sort(onlik)
tartiblanganlar

array([0.04666566, 0.09060643, 0.23277134, 0.38246199, 0.39986097,
       0.46676289, 0.61838601, 0.85994041, 0.97375552, 0.98323089])

#### 22. Ikki tasodifiy A va B massiv yarating, ularning tengligini tekshiring

`💡Ishora` np.allclose, np.array_equal

In [23]:
A = np.random.rand()
B = np.random.rand()
np.allclose(A,B)


False

#### 23. O'lchamlari 6x3 va 3x4 matritsa tuzing va ularni o'zaro ko'paytiring.


`💡Ishora` np.dot or np.ones

In [12]:
z = np.random.rand(6,3)
x = np.random.rand(3,4)
np.dot(z,x)

array([[0.41639736, 0.3757161 , 0.63814162, 0.9631171 ],
       [0.55481349, 0.76158124, 0.41761677, 0.36277429],
       [0.53975374, 0.68620665, 0.42643581, 0.36250006],
       [0.50105978, 0.45861592, 0.59828877, 0.72310823],
       [0.48903686, 0.49449444, 0.62100914, 0.83885173],
       [0.57787667, 0.55353249, 0.66937263, 0.79957383]])

#### 24. Tasodifiy sonlardan iborat bo'lgan o'lchami 5 ga teng vektor yarating, so'ng uning eng katta qiymatini 0 ga o'zgartiring.


`💡Ishora` argmax

In [16]:
vector1 = np.random.rand(5)
print(vector1)
the_bigest = np.argmax(vector1)*0
print(the_bigest)

[0.04097125 0.87674055 0.60901151 0.68975279 0.25081687]
0


#### 25. NumPy kutubxonasi yordamida kecha, bugun va ertangi kun sanalarini aniqlang.


`💡Ishora` np.datetime64, np.timedelta64

In [1]:
import numpy as np

# Bugungi kunni topish
bugun = np.datetime64('today', 'D')

# Kechagi kunni hisoblash
kecha = bugun - np.timedelta64(1, 'D')

# Ertaga kunni hisoblash
ertaga = bugun + np.timedelta64(1, 'D')

# Javoblarni chop etish
print("Kechagi kun:", kecha)
print("Bugungi kun:", bugun)
print("Ertangi kun:", ertaga)


Kechagi kun: 2023-07-15
Bugungi kun: 2023-07-16
Ertangi kun: 2023-07-17


#### 26. 2016 yil yanvar oyiga to'g'ri keladigan barcha sanalarni NumPy kutubxonasi yordamida aniqlang.


`💡Ishora` np.arange(dtype=datetime64['D'])

In [28]:
kunlar = np.arange(np.datetime64('2016-01-01'),np.datetime64('2016-01-31'))
print(kunlar)

['2016-01-01' '2016-01-02' '2016-01-03' '2016-01-04' '2016-01-05'
 '2016-01-06' '2016-01-07' '2016-01-08' '2016-01-09' '2016-01-10'
 '2016-01-11' '2016-01-12' '2016-01-13' '2016-01-14' '2016-01-15'
 '2016-01-16' '2016-01-17' '2016-01-18' '2016-01-19' '2016-01-20'
 '2016-01-21' '2016-01-22' '2016-01-23' '2016-01-24' '2016-01-25'
 '2016-01-26' '2016-01-27' '2016-01-28' '2016-01-29' '2016-01-30']


#### 27. 4 xil usul yordamida musbat sonlarning tasodifiy massivining butun son qismini ajratib oling.


`💡Ishora` %, np.floor, astype, np.trunc`

In [2]:
array = np.random.rand(10)*10

print("Asl array:")
print(array)

# Birinchi usul: %
usul1 = array % 1
print("\nUsul 1 (%):")
print(usul1)

# Ikkinchi usul: np.floor()
usul2 = np.floor(array)
print("\nUsul 2 (np.floor()):")
print(usul2)

# Uchinchi usul: astype(int)
usul3 = array.astype(int)
print("\nUsul 3 (astype(int)):")
print(usul3)

# To`rtinchi usul: np.trunc()
usul4 = np.trunc(array)
print("\nUsul 4 (np.trunc()):")
print(usul4)

Asl array:
[2.84252327 7.30712612 2.4284728  5.17117371 4.64931637 2.88216349
 5.41102301 9.93507382 0.52121286 6.03154993]

Usul 1 (%):
[0.84252327 0.30712612 0.4284728  0.17117371 0.64931637 0.88216349
 0.41102301 0.93507382 0.52121286 0.03154993]

Usul 2 (np.floor()):
[2. 7. 2. 5. 4. 2. 5. 9. 0. 6.]

Usul 3 (astype(int)):
[2 7 2 5 4 2 5 9 0 6]

Usul 4 (np.trunc()):
[2. 7. 2. 5. 4. 2. 5. 9. 0. 6.]


#### 28. Ixtiyoriy kichik massivlar yarating, ular yeg'indisini np.sum funksiyasidanda tezroq hisoblovchi dastur tuzing.


`💡Ishora` np.add.reduce

In [20]:
massiv1 = np.arange(3)
jami = np.add.reduce(massiv1)
print(jami)

3


#### 29. [1, 2, 3, 4, 5] vektor berilgan, har bir qiymat orasiga ketma-ket 3 ta nol raqamini yozuvchi dastur tuzing.


`💡Ishora` array[::4]

In [31]:
vektor = [1, 2, 3, 4, 5]
javob = []

for raqam in vektor:
    javob.extend([raqam, 0, 0, 0])

# Ohirgi 3 noni olib tashlaymiz
javob = javob[:-3]

print(javob)


[1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 4, 0, 0, 0, 5]


#### 30. Quyidagi a massiv berilgan, a = [1,2,3,4,5,6,7,8,9,10,11,12,13,14] undan foydalangan holda siz quyidagi b massivni yarata olasizmi, b = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]?


`💡Ishora` stride_tricks.as_strided

In [11]:
from numpy.lib.stride_tricks import as_strided

# array tuzish
a = [1,2,3,4,5,6,7,8,9,10,11,12,13,14]
a = np.array(a)

# O`lchamni kiritish
olcham = 4

# Yangi oyna ko'rinishi uchun yangi shakl va qadamlarni hisoblang
shakl = (a.size - olcham + 1, olcham)
qadamlar = (a.itemsize, a.itemsize)

# Yangi array
b = as_strided(a, shape = shakl, strides = qadamlar)
print(b)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 31. Ixtiyoriy sonlardan tashkil topgan massiv yarating, unga o'xshash qiymatlar kiriting. So'ng, o'xshash qiymatlarni topuvchi dastur tuzing.


`💡Ishora` np.bincount, argmax

In [33]:
import numpy as np

def create_array(length):
  """Yasalgan arrayni uzunligini random raqamlar orqali topiladi"""
  array = []
  for i in range(length):
    array.append(random.randint(0, 100))
  return array

def find_similar_values(array):
  """O`xshash qiymatlarni np.bincount va argmax orqalik topaylik."""
  counts = np.bincount(array)
  similar_values = []
  for i in range(len(counts)):
    if counts[i] > 1:
      similar_values.append(i)
  return similar_values

array = create_array(10)
print(array)
similar_values = find_similar_values(array)
print(similar_values)


[1, 83, 91, 59, 70, 43, 7, 46, 34, 77]
[]


#### BONUS!

`💡O'zingiz javob berishni istagan savolni kiriting va unga javob bering!`

In [25]:
import numpy as np
# Numpy yordamida unit testing!
from numpy.testing import assert_allclose

arr1 = np.array([0.1, 0.2, 0.3])
arr2 = np.array([0.10002, 0.8888, 0.31222])
assert_allclose(arr1, arr2, rtol=1e+4)  # No error will be raised

arr3 = np.array([0.1, 0.2, 0.3])
assert_allclose(arr1, arr3, rtol=1e-5)  # AssertionError: Not all elements are close
